# Generated by Django 2.2.3 on 2019-09-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loggeduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggeduser',
            name='emailid',
        ),
    ]
