# Generated by Django 2.2.3 on 2019-10-01 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_chatroom_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='posted_date',
        ),
    ]
